#服务器端口
server:
   port: 8002
   servlet:
      context-path: /demoMicroservice  # 请求接口的前缀
# Spring
spring:
   application:
      # 应用名称
      name: cpms-server-demo
   #********以下配置为了捕获 NoHandlerFoundException 异常信息 start ****#
   mvc:
      throw-exception-if-no-handler-found: true
   resources:
      add-mappings: false
   #********以下配置为了捕获 NoHandlerFoundException 异常信息 end ****#

   #******** 激活自定义配置文件 ****#
   profiles:
      include: system,jdbc

   cloud:
      nacos:
         #      config:
         #        server-addr: 120.0.0.1:8848
         #        file-extension: yaml
         #        prefix: nacos
         discovery: # 服务发现注册
            server-addr: 127.0.0.1:8858

# xxl-job配置
xxl:
   job:
      admin:
         addresses: http://127.0.0.1:8080/xxl-job-admin
      accessToken: ''
      executor:
         # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
         address:
         # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
         appname: demo-app
         # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
         ip:
         # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
         port: 0
         # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
         logpath: E:\developCode\test\MMMM\xxl-job-log
         # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
         logretentiondays: 15

