#服务器端口
server:
  port: 8001
  servlet:
    context-path: /systemMicroservice  # 请求接口的前缀
# Spring
spring:
  application:
    # 应用名称
    name: cpms-server-system
  cloud:
    nacos:
      #      config:
      #        server-addr: 120.0.0.1:8848
      #        file-extension: yaml
      #        prefix: nacos
      discovery: # 服务发现注册
        server-addr: 127.0.0.1:8858