#服务器端口
server:
   port: 5003
   servlet:
      context-path: /monitorService  # 请求接口的前缀

# Spring
spring:
   application:
      # 应用名称
      name: cpms-monitor-admin
   mvc:
      ## 配置为了捕获 NoHandlerFoundException 异常信息
      throw-exception-if-no-handler-found: true

   #******** 激活自定义配置文件 ****#
   profiles:
      active: dev

   cloud:
      nacos:
         discovery: # 服务发现注册
            server-addr: localhost:8858
            metadata: # 由于配置了context-path，所以这里需要设置，否则监控不到
               management:
                  context-path: ${server.servlet.context-path}/actuator
               user.name: "monitor"
               user.password: "monitor"
   security:
      user:
         name: "monitor"
         password: "monitor"
      boot:
         admin:
            context-path: "control"



management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always


