server:
  port: 6001
  servlet:
    context-path: /authMicroservice
spring:
  application:
    name: cpms-server-auth
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: @profiles.active@
    include: redis,system

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8858

feign:
  hystrix:
    enabled: true

ribbon:
  OkToRetryOnAllOperations: false
  ReadTimeout:  5000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  http:
    client:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000
    ISysUserClient#sysUserLogin(SysUserLginDTO):
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000
  shareSecurityContext: true

cpms:
  jwt-secretKey: cpms
  jwt-token-expire: 3600*2*1000  # token有效期，单位：毫秒

