server:
  port: 6001
  servlet:
    context-path: /authMicroservice
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    include: redis,system


feign:
  sentinel:
    enabled: true

ribbon:
  OkToRetryOnAllOperations: false
  ReadTimeout:  5000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  http:
    client:
      enabled: true


cpms:
  jwt-secretKey: cpms
  jwt-token-expire: 7200000  # token有效期，单位：毫秒

