#服务器端口
server:
  port: 6001
  servlet:
    context-path: /authMicroservice  # 请求接口的前缀
# Spring应用基础配置
spring:
  application:
    # 应用名称
    name: cpms-server-auth
  cloud:
    nacos:
#      config:
#        server-addr: 120.0.0.1:8848
#        file-extension: yaml
#        prefix: nacos
      discovery: # 服务发现注册
        server-addr: 127.0.0.1:8858


# 开启hystrix熔断
feign:
  hystrix:
      enabled: true

#【注：接口调用时间超过ribbon或者hystrix配置的超时时间都会触发熔断，一般设置ribbon的超时时间需要大于hystrix配置的超时时间，
#  这样的话我们可以针对具体的接口做超时熔断限制，否则的话所有的接口都会根据ribbon的设置触发熔断】

#ribbon配置
ribbon:
  #对所有操作请求都进行重试,默认false
  OkToRetryOnAllOperations: false  # 默认关闭
  #两个服务建立连接后，本地服务等待接收远程服务返回数据时的超时时间，业务程序会影响接收时间，同时这个设置也是触发熔断的时间设置
  ReadTimeout:  5000  #本地服务等待接收远程服务返回数据最大所用时间，默认值5000
  #表示两个服务建立起http网络服务连接的时间，此过程一般是很快的，业务程序不会影响连接时间
  ConnectTimeout: 2000  #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0    #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1
  # 如果不添加 ribbon.http.client.enabled=true，那么 ribbon 的默认配置不会生效
  http:
    client:
      enabled: true

#hystrix降级熔断配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000  # 这个超时针对具体的接口做超时熔断处理