#服务器端口
server:
   port: 8002
   servlet:
      context-path: /logMicroservice  # 请求接口的前缀
# Spring
spring:
   application:
      # 应用名称
      name: cpms-server-log
   #********以下配置为了捕获 NoHandlerFoundException 异常信息 start ****#
   mvc:
      throw-exception-if-no-handler-found: true
   resources:
      add-mappings: false
   #********以下配置为了捕获 NoHandlerFoundException 异常信息 end ****#

   cloud:
      nacos:
         #      config:
         #        server-addr: 120.0.0.1:8848
         #        file-extension: yaml
         #        prefix: nacos
         discovery: # 服务发现注册
            server-addr: 127.0.0.1:8858
   # 数据源配置
   datasource:
      url: jdbc:mysql://localhost:3306/cpms-cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver