management:
   health:
      mail:
         enabled: false
   server:
      base-path: /actuator
server:
   port: 8003
   servlet:
      context-path: /xxl-job-admin
spring:
   profiles:
      active: @profiles.active@
      include: jdbc
   freemarker:
      charset: UTF-8
      request-context-attribute: request
      settings:
         number_format: 0.##########
      suffix: .ftl
      templateLoaderPath: classpath:/templates/
   mail:
      from: xxx@qq.com
      host: smtp.qq.com
      password: xxx
      port: 25
      properties:
         mail:
            smtp:
               auth: true
               socketFactory:
                  class: javax.net.ssl.SSLSocketFactory
               starttls:
                  enable: true
                  required: true
      username: xxx@qq.com
   mvc:
      servlet:
         load-on-startup: 0
      static-path-pattern: /static/**
   web:
      resources:
         static-locations: classpath:/static/
xxl:
   job:
      accessToken: ''
      i18n: zh_CN
      logretentiondays: 30
      triggerpool:
         fast:
            max: 200
         slow:
            max: 100
